NativeScript/nativescript-sdk-examples-js

- app/data-category/observable/mvvm-pattern/article.md
- app/file-system/create/article.md
- app/http/post/article.md
- app/platform/basics/article.md
- app/timer/overview.md
- app/ui-category/activity-indicator/code-behind/article.md
- app/ui-category/activity-indicator/styling/article.md
- app/ui-category/button/styling/article.md
- app/ui-category/date-picker/basics/article.md
- app/ui-category/date-picker/styling/article.md
- app/ui-category/dialogs/action/article.md
- app/ui-category/dialogs/end.md
- app/ui-category/dialogs/overview.md
Addresses [docs/#1155](https://github.com/NativeScript/docs/issues/1155)
> docs: fix action example being used

- app/ui-category/tab-view/styling/styling-page.xml
selectedColor property is now selectedTabTextColor. Changed sample to reflect that.
> sample: fix outdated property name

- package.json
Update runtimes.
Update webpack.
> chore: update versions

- app/App_Resources/Android/AndroidManifest.xml
- app/App_Resources/iOS/Info.plist
- app/app.js
- app/delegate/my-delegate.js
- app/shared/deep-link-data.js
Starting iOS app ->`xcrun simctl openurl booted examplesgo://org.nativescript.nativescriptsdkexamplesjs?gotoexample=ns-ui-widgets-category/button/basics/basics-page`
Starting Android app ->`am start -a android.intent.action.VIEW -d "examplesgo://js?gotoexample=ns-ui-widgets-category/button/basics/basics-page" org.nativescript.nativescriptsdkexamplesjs`
> deep-link functionality

- app/ns-ui-widgets-category/image/overview.md
related to [https://github.com/NativeScript/docs/pull/1259](https://github.com/NativeScript/docs/pull/1259)
> add supported images note

- app/ns-framework-modules-category/file-system/create/article.md
- app/ns-framework-modules-category/file-system/delete/article.md
Related to feedback form report for non-working snippet in Delete section [https://github.com/NativeScript/docs/issues/1334](https://github.com/NativeScript/docs/issues/1334)
> fix: broken snippet id

- app/ns-ui-widgets-category/switch/basics/article.md
- app/ns-ui-widgets-category/switch/basics/basics-page.css
- app/ns-ui-widgets-category/switch/basics/basics-page.js
- app/ns-ui-widgets-category/switch/basics/basics-page.xml
- app/ns-ui-widgets-category/switch/code-behind/article.md
- app/ns-ui-widgets-category/switch/code-behind/code-behind-page.css
- app/ns-ui-widgets-category/switch/code-behind/code-behind-page.js
- app/ns-ui-widgets-category/switch/code-behind/code-behind-page.xml
Related to feedback form request [https://github.com/NativeScript/docs/issues/1334](https://github.com/NativeScript/docs/issues/1334)
> docs: improved Switch snippets

- app/ns-framework-modules-category/console/basics/basics-page.js
https://github.com/NativeScript/docs/issues/1290
> console.dir example

- app/ns-framework-modules-category/timer/interval/article.md
- app/ns-framework-modules-category/timer/interval/interval-page.js
- app/ns-ui-widgets-category/list-view/code-behind/code-behind-page.js
https://github.com/NativeScript/docs/issues/1290
> extending snippets - timer module

- app/ns-framework-modules-category/console/basics/basics-page.js
- app/ns-ui-widgets-category/layouts/flexbox-layout-one/article.md
- app/ns-ui-widgets-category/layouts/flexbox-layout-one/flexbox-layout-page.xml
- app/ns-ui-widgets-category/layouts/flexbox-layout-three/article.md
- app/ns-ui-widgets-category/layouts/flexbox-layout-three/flexbox-layout-page.xml
- app/ns-ui-widgets-category/layouts/flexbox-layout-two/article.md
- app/ns-ui-widgets-category/layouts/flexbox-layout-two/flexbox-layout-page.xml
- app/ns-ui-widgets-category/layouts/flexbox-layout/article.md
- app/ns-ui-widgets-category/layouts/flexbox-layout/flexbox-layout-page.xml
- app/ns-ui-widgets-category/layouts/layouts-page.js
- app/ns-ui-widgets-category/time-picker/time-format/time-format-page.js
flexbox examples/ eslint errors
> flexbox examples/ eslint errors

- app/ns-framework-modules-category/file-system/create/article.md
- app/ns-framework-modules-category/file-system/overview.md
Fixes https://github.com/NativeScript/docs/issues/1111 but as a result of this review I really think we should do 
https://github.com/NativeScript/NativeScript/issues/6260
> docs: update fs module overview

- app/ns-ui-widgets-category/web-view/basics/basics-page.js
- app/ns-ui-widgets-category/web-view/basics/basics-page.xml
- app/ns-ui-widgets-category/web-view/events/article.md
- app/ns-ui-widgets-category/web-view/events/events-page.css
- app/ns-ui-widgets-category/web-view/events/events-page.js
- app/ns-ui-widgets-category/web-view/events/events-page.xml
- app/ns-ui-widgets-category/web-view/gestures/article.md
- app/ns-ui-widgets-category/web-view/gestures/gestures-page.xml
- app/ns-ui-widgets-category/web-view/source-load/source-load-page.js
- app/ns-ui-widgets-category/web-view/web-view-page.js
> WebView examples

- package.json
Related to failing webpack build with CSS-loader error
> removing obsolete developer depedencies

- app/ns-ui-widgets-category/web-view/end.md
Fixes one item in NativeScript/docs#1241.
See also nativescript-vue/nativescript-vue.org#32 and NativeScript/docs#1385.
> docs: update the article (UIWebView -> WKWebView)

- app/ns-ui-widgets-category/layouts/wrap-layout/article.md
> Fix wrap-layout broken link

- app/ns-ui-widgets-category/label/basics/article.md
Nothing critical, noticed a grammatical error here while reading through the docs. Happy to contribute back :)
> Simple grammatical error

- app/ns-framework-modules-category/console/overview.md
iOS Speicifics: -> iOS Specifics
> Correct spelling mistake.

- app/ns-ui-widgets-category/list-view/metadata.md
- app/ns-ui-widgets-category/list-view/multiple-templates-selector-function/article.md
- app/ns-ui-widgets-category/list-view/multiple-templates-selector-function/multiple-templates-selector-function-page.js
- app/ns-ui-widgets-category/list-view/multiple-templates-selector-function/multiple-templates-selector-function-page.xml
- app/ns-ui-widgets-category/list-view/multiple-templates-selector-function/multiple-templates-selector-function-ts-page.ts
- app/ns-ui-widgets-category/list-view/multiple-templates-selector-function/multiple-templates-selector-function-ts-page.xml
- app/ns-ui-widgets-category/list-view/multiple-templates/article.md
- app/ns-ui-widgets-category/list-view/multiple-templates/multiple-templates-page.xml
> ListView examples order

- app/ns-ui-widgets-category/tab-view/styling/article.md
- app/ns-ui-widgets-category/tab-view/styling/styling-page.xml
provides docs example for https://github.com/NativeScript/NativeScript/pull/5752
> docs: tabTextFontSize example added

- app/ns-ui-widgets-category/dialogs/login/login-page.js
- app/ns-ui-widgets-category/dialogs/login/login-ts-page.ts
- app/ns-ui-widgets-category/placeholder/platform-files/platform-files-ts-page.ios.ts
- app/ns-ui-widgets-category/repeater/basics/basics-ts-page.ts
MERGE AFTER [https://github.com/NativeScript/NativeScript/pull/6416](https://github.com/NativeScript/NativeScript/pull/6416) is live
Related to [https://github.com/NativeScript/NativeScript/pull/6416](https://github.com/NativeScript/NativeScript/pull/6416)
> [DO NOT MERGE] Hints in login dialog

- app/ns-ui-widgets-category/dialogs/prompt/prompt-page.js
- app/ns-ui-widgets-category/dialogs/prompt/prompt-ts-page.ts
Related to [https://github.com/NativeScript/NativeScript/pull/6325](https://github.com/NativeScript/NativeScript/pull/6325)
Related to [https://github.com/NativeScript/NativeScript/pull/6365](https://github.com/NativeScript/NativeScript/pull/6365)
> docs: capitalization and input types for prompt dialogs

- app/home/home-page.css
- app/home/home-page.xml
- app/ns-ui-widgets-category/action-bar/hide-show-actionbar/article.md
- app/ns-ui-widgets-category/frame/action-bar-visibility/actionbar-visibility-page.css
- app/ns-ui-widgets-category/frame/action-bar-visibility/actionbar-visibility-page.xml
- app/ns-ui-widgets-category/frame/action-bar-visibility/article.md
- app/ns-ui-widgets-category/frame/frame-page.js
> actionBarVisibility example

- app/ns-ui-widgets-category/action-bar/basics/article.md
<ActionBar title="Basics"/> - is not working in any case it generates error
<ActionBar title="Basics"></ActionBar> should be instead
> Teks is OK but a code sample is not correct in any case

- app/ns-ui-widgets-category/list-view/overview.md
- app/ns-ui-widgets-category/scroll-view/overview.md
using ListView in ScrollView/ScrollView in ScrollView note
> using ListView in ScrollView/ScrollView in ScrollView

- app/ns-ui-widgets-category/layouts/stack-layout/article.md
- app/ns-ui-widgets-category/segmented-bar/metadata.md
- app/ns-ui-widgets-category/tab-view/basics/article.md
- app/ns-ui-widgets-category/text-field/keyboard-type/article.md
> broken links fix

- app/App_Resources/iOS/Info.plist
- package.json
added `CFBundleTypeRole` to remove a build warning about missing key.
> chore: version bump + minor info.plist update

- app/ns-framework-modules-category/application/android-broadcast-receiver/android-broadcast-receiver-page.js
- app/ns-framework-modules-category/application/android-broadcast-receiver/android-broadcast-receiver-ts-page.ts
- app/ns-framework-modules-category/application/application-events/application-events-page.js
- app/ns-framework-modules-category/application/application-events/application-events-ts-page.ts
Related to https://github.com/NativeScript/NativeScript/issues/7154
> docs: update application events OFF example

- app/ns-ui-widgets-category/image/stretching/article.md
Clipping will be performed on aspectFill not aspectFilt.
> aspectFit and aspectFill clip information

- app/ns-ui-category/modal-view/basics/basics-page.js
- app/ns-ui-category/modal-view/basics/basics-ts-page.ts
- app/ns-ui-category/modal-view/custom-actionbar/main-page.js
- app/ns-ui-category/modal-view/custom-actionbar/main-ts-page.ts
- app/ns-ui-category/modal-view/modal-navigation/main-page.js
- app/ns-ui-category/modal-view/modal-navigation/main-ts-page.ts
- app/ns-ui-category/modal-view/modal-navigation/modal-root.js
- app/ns-ui-category/modal-view/modal-navigation/modal-ts-root.ts
setting up ShowModalOptions in the modal view samples
> setting up ShowModalOptions in the modal view samples

- app/ns-framework-modules-category/http/post/post-page.js
> update short import

- app/ns-framework-modules-category/application-settings/native-access/native-access-ts-page.ts
- app/ns-framework-modules-category/application/android-broadcast-receiver/android-broadcast-receiver-ts-page.ts
- app/ns-framework-modules-category/application/ios-notification-observer/ios-notification-observer-ts-page.ts
Related to http://nsbuild01:8080/build/view/Master%20View/view/02.%20Android%20Applications/job/master-nativescript-sdk-examples-js-android/386/console
> fix: deprecated APIs removed

- app/App_Resources/Android/app.gradle
- app/ns-ui-widgets-category/tab-view/end.md
Merge after releasing AndroidX in the official version of `tns-core-modules`
> [DO NOT MERGE] AndroidX update

- app/ns-ui-widgets-category/animations/animating-properties/article.md
more info about animation properties
> FR: more info about animation properties

- app/ns-ui-widgets-category/bottom-navigation/styling/styling-page.xml
- app/ns-ui-widgets-category/tabs/end.md
- app/ns-ui-widgets-category/tabs/styling/article.md
- app/ns-ui-widgets-category/tabs/styling/styling-page.css
- app/ns-ui-widgets-category/tabs/styling/styling-page.xml
- package.json
> feat: highlightColor example

- app/links-view-model.js
- app/ns-framework-modules-category/application/application-events/application-events-page.xml
- app/ns-framework-modules-category/application/application-events/application-events-ts-page.xml
- app/ns-framework-modules-category/application/application-page.js
- app/ns-framework-modules-category/application/check-platform/check-platform-page.js
- app/ns-framework-modules-category/application/check-platform/check-platform-ts-page.ts
- app/ns-ui-widgets-category/action-bar/styling/styling-page.js
- app/ns-ui-widgets-category/action-bar/usage/usage-page.js
- app/ns-ui-widgets-category/action-bar/usage/usage-ts-page.ts
- app/ns-ui-widgets-category/frame/frame-reference/frame-reference-page.js
- app/ns-ui-widgets-category/frame/frame-reference/frame-reference-ts-page.ts
- package.json
- webpack.config.js
Updated dependencies to latest + improved some snippet and navigation logic.
> chore: update dependencies & obsolete code snippets

- app/ns-ui-widgets-category/formatted-string/end.md
- app/ns-ui-widgets-category/formatted-string/usage/article.md
FIxes broken links caught by the crawler.
> fix: broken links fix

- app/ns-ui-widgets-category/bottom-navigation/styling/styling-page.css
- app/ns-ui-widgets-category/bottom-navigation/styling/styling-page.xml
- app/ns-ui-widgets-category/tabs/styling/article.md
- app/ns-ui-widgets-category/tabs/styling/styling-page.css
- app/ns-ui-widgets-category/tabs/usage/article.md
Tabs styling options revised.
Adds **highlightColor**, **selectedItemColor**, and **unSelectedItemColor** properties example.
> docs: add Tabs/BottomNavigaiton styling options

- app/ns-ui-widgets-category/bottom-navigation/overview.md
There is a little mistake in documentation.
> Updated overview.md

- app/ns-ui-widgets-category/text-field/end.md
> docs: Update end.md

- app/ns-framework-modules-category/application/android-broadcast-receiver/android-broadcast-receiver-page.js
- app/ns-framework-modules-category/application/android-broadcast-receiver/android-broadcast-receiver-ts-page.ts
> docs: typo fix in android-broadcast-receiver-page.js
